### ISSUE TITLE
Slideshow-Issues

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1151]
Sammel-Issue für alle Slideshow-Aufgaben:

- [x] #1064 - Slideshow grid 
- [x] #1045 - Bilder je nach Bildschirmgröße anzeigen 
- [x] #1044 - Image Toolbar in der Slideshow 
- [ ] #976 - Slideshow Categories 
- [x] #971 - Slideshow toolbar 
- [x] #941 - Slideshow link behaviour 
- [ ] #940 - Slideshow link styling slideshow
- [x] #931 - Slideshow Scroll-"Problem" (mobile Geräte)
- [x] #1152 - Slideshow-Select-Kacheln

Vielleicht braucht es für einige Issues Rückfragen, aber viele sind auch klar. Ggf. Kerstin per mention fragen, vielleicht weiß sie weiter.

**Comment by anhnguyen-98** [comment]
Close via #1215
