### ISSUE TITLE
Quiz final sprint

### ISSUE THREAD

**Issue by sheepyhollow** [zentrumnawi/solid-frontend#1630]
Folgende Punkte sind noch am Quiz zu lösen:

- [x] Quiz [Toolbar Issues](https://github.com/zentrumnawi/solid-frontend/issues/1547#issuecomment-1169883415) 

#### quiz/start.component
- [x] difficulty slider `max = 30` und `default = 10`
- [x] Überschriften [immer in eigener Zeile](https://github.com/zentrumnawi/solid-frontend/issues/1556#issuecomment-1172936925)
- [x] [einheitliche Margins](https://github.com/zentrumnawi/solid-frontend/issues/1556#issuecomment-1173066676) im Expertenmodus (alle Elemente, Überschriften, Tags, Buttons...) auf einer Linie (low priority)
- [x] Reset Icon rechtsbündig und `disabled` (grau), wenn kein Tag/Difficulty ausgewählt ist (low priority)
- [ ] [Expertenmodus-State erhalten](https://github.com/zentrumnawi/solid-frontend/issues/1557#issuecomment-1175078550), so lange der User im Quiz ist, also bei Quiz restart (low priority)

#### quiz/question.component
- [x] [skip-to-eval Dialog](https://github.com/zentrumnawi/solid-frontend/issues/1487#issuecomment-1175119012) (medium priority)

#### quiz/single-choice-question.component
- [x] [Single-Choice Feedback Icons Bug](https://github.com/zentrumnawi/solid-frontend/pull/1520#issuecomment-1173448655)

#### quiz/end.component
- [x] Farben für correct/incorrect/unanswered-Icons in der Quiz-Auswertung
- [x] [Back- und Restart-Buttons](https://github.com/zentrumnawi/solid-frontend/issues/1557#issuecomment-1175075081)

**Comment by sheepyhollow** [comment]
Ich habe ein bisschen herumprobiert, das mit dem Expertenmodus im State zu lösen. Aber das State-Management mit `ngxs` ist zu kompliziert für mich... Ich habe nicht genau verstanden, was man machen muss, um eine einfache Variable zu setzen. Mit einem `@Selector` lesen und mit einer `@Action` ändern... 🤷‍♂️ 

Verschwende keine Zeit damit. Wenn Du ungefähr weißt, wie es geht, dann los. Aber wenn es zu lange dauert, um eine Lösung zu suchen, dann lass es weg und wir liefern das Feature irgendwann später nach.
